[package]
name = "zcash_proofs"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]

[dependencies]
bellman = { path = "../bellman" }
pairing = { path = "../pairing" }
sapling-crypto = { path = "../sapling-crypto" }
