[package]
name = "zcash_primitives"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]

[dependencies]
byteorder = "1"
lazy_static = "1"
pairing = { path = "../pairing" }
sapling-crypto = { path = "../sapling-crypto" }
